# Generated by Django 5.0.3 on 2024-03-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_register_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From1', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
            ],
        ),
    ]
